version: '3.9'

services:
postgres:
image: postgres
env_file:
- .env
volumes:
- './postgres:/var/lib/postgresql/data'
ports:
- '5432:5432'

web:
build:
  context: .
  dockerfile: Dockerfile
# command: ["npm", "run", "create"]
links:
- postgres
image: storefront
depends_on:
- postgres
ports:
- '3000:3000'
env_file:
- .env

volumes:
postgres: